<a href="https://colab.research.google.com/github/Abhishek0077-cs/Reliance-TCS-stock-analysis-1995-2025/blob/main/Stock_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#The 2008 Financial Crisis (The "Deep" Crash)
Context: Triggered by the US housing bubble and the collapse of Lehman Brothers. The Indian Nifty fell ~64% over 10 months.

Reliance Performance: Hit hard due to its high debt at the time and its sensitivity to global oil demand. Reliance was at the center of the industrial economy, which slowed down significantly.

TCS Performance: While it also fell, the impact was different. Global banks (TCS’s biggest clients) slashed IT budgets. However, TCS’s zero-debt balance sheet allowed it to survive without the risk of insolvency.

Recovery: This was a "U-shaped" recovery. It took the broader market nearly 6 years to fully break the 2008 peak again.

# The 2020 COVID-19 Pandemic (The "Fast" Crash)
Context: A sudden, global lockdown. The Nifty fell ~40% in just 3 months (January to March).

Reliance Performance: This was the "Jio Moment." While the stock initially dipped, it staged one of the fastest recoveries in history. Why? Because while people stopped driving (hurting oil), they started using massive amounts of data. Reliance raised over ₹2 lakh crore in the middle of the pandemic from investors like Google and Facebook.

TCS Performance: TCS became the "Digital Lifeline." As companies worldwide had to move to the cloud overnight, TCS's order book hit record highs. It proved to be incredibly resilient, with its "Work from Anywhere" model.

Recovery: A classic "V-shaped" recovery. The market bounced back to pre-pandemic levels in just 6 to 11 months

#Use Case,Objective
Portfolio Rebalancing,Deciding whether to shift weight toward the stability of TCS (IT services) or the aggressive growth of Reliance (Telecom/Retail/Energy).
Crisis Resilience Check,"Evaluating how both stocks behaved during the 2008 Financial Crisis and the 2020 Pandemic to assess ""safe haven"" status."
Dividend vs. Growth Strategy,Comparing TCS (traditionally a high-dividend payer) against Reliance (which reinvests heavily into new business verticals).
Sectoral Hedging,Understanding the lack of correlation between the O2C/Telecom sector (Reliance) and Global IT spending (TCS) to diversify risk.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [45]:
Stock_df = pd.read_csv('India_Stock.csv')
Stock_df.head(100)

    Year              Company    Open    High     Low   Close    Volume
0   1995  Reliance Industries  106.18  113.89   91.06  109.48  43442631
1   1996  Reliance Industries  109.48  137.72  103.13  125.41   2008640
2   1997  Reliance Industries  125.41  140.53  111.56  134.63  26713065
3   1998  Reliance Industries  134.63  156.18  119.53  145.13  30980791
4   1999  Reliance Industries  145.13  168.23  131.96  157.57  39473622
..   ...                  ...     ...     ...     ...     ...       ...
95  2000              Infosys  347.92  416.27  308.99  386.04  17104562
96  2001              Infosys  386.04  525.67  367.77  468.14   5469099
97  2002              Infosys  468.14  600.65  401.42  553.96  27926915
98  2003              Infosys  553.96  707.20  479.30  663.65   8006592
99  2004              Infosys  663.65  823.00  617.44  735.48   5955011

[100 rows x 7 columns]

In [6]:
Reliance_df = Stock_df[Stock_df['Company']=='Reliance Industries']
Reliance_df.head(30)

    Year              Company     Open     High      Low    Close    Volume
0   1995  Reliance Industries   106.18   113.89    91.06   109.48  43442631
1   1996  Reliance Industries   109.48   137.72   103.13   125.41   2008640
2   1997  Reliance Industries   125.41   140.53   111.56   134.63  26713065
3   1998  Reliance Industries   134.63   156.18   119.53   145.13  30980791
4   1999  Reliance Industries   145.13   168.23   131.96   157.57  39473622
5   2000  Reliance Industries   157.57   174.81   144.47   167.12  30028313
6   2001  Reliance Industries   167.12   196.78   143.47   188.81  47495391
7   2002  Reliance Industries   188.81   233.33   180.33   203.69  15926074
8   2003  Reliance Industries   203.69   250.85   176.36   232.87  25263668
9   2004  Reliance Industries   232.87   255.07   225.47   248.97  13680219
10  2005  Reliance Industries   248.97   275.88   229.32   253.65  10057868
11  2006  Reliance Industries   253.65   350.98   241.16   306.25  47035448
12  2007  Reliance Industries   306.25   397.07   263.84   348.36  10603160
13  2008  Reliance Industries   348.36   425.47   310.84   414.73  20045187
14  2009  Reliance Industries   414.73   522.71   367.67   490.17  27592108
15  2010  Reliance Industries   490.17   548.12   467.76   527.89   4652981
16  2011  Reliance Industries   527.89   686.50   501.63   615.82   4628187
17  2012  Reliance Industries   615.82   782.30   532.72   733.45  43292067
18  2013  Reliance Industries   733.45   754.18   652.66   732.98  16933982
19  2014  Reliance Industries   732.98   987.10   683.78   885.41  44473424
20  2015  Reliance Industries   885.41  1021.65   840.17   918.15  28502582
21  2016  Reliance Industries   918.15  1145.72   839.37  1022.76  26613908
22  2017  Reliance Industries  1022.76  1150.74   873.52  1112.87  32184110
23  2018  Reliance Industries  1112.87  1316.54  1019.52  1241.00  45470757
24  2019  Reliance Industries  1241.00  1494.91  1091.76  1336.86   4772015
25  2020  Reliance Industries  1336.86  1414.52  1164.35  1337.39  46555184
26  2021  Reliance Industries  1337.39  1758.33  1276.51  1551.53  10141932
27  2022  Reliance Industries  1551.53  2137.41  1427.59  1881.47  40564567
28  2023  Reliance Industries  1881.47  2131.39  1655.00  2060.69  21928281
29  2024  Reliance Industries  2060.69  2724.56  1982.17  2418.95   1340654

In [7]:
Reliance_df['Mean'] = Reliance_df[['Close','Open','High','Low']].mean(axis=1)
Mean_df= Reliance_df[['Year','Mean']]
Mean_df.head(30)

/tmp/ipykernel_395/1923383241.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Reliance_df['Mean'] = Reliance_df[['Close','Open','High','Low']].mean(axis=1)

    Year       Mean
0   1995   105.1525
1   1996   118.9350
2   1997   128.0325
3   1998   138.8675
4   1999   150.7225
5   2000   160.9925
6   2001   174.0450
7   2002   201.5400
8   2003   215.9425
9   2004   240.5950
10  2005   251.9550
11  2006   288.0100
12  2007   328.8800
13  2008   374.8500
14  2009   448.8200
15  2010   508.4850
16  2011   582.9600
17  2012   666.0725
18  2013   718.3175
19  2014   822.3175
20  2015   916.3450
21  2016   981.5000
22  2017  1039.9725
23  2018  1172.4825
24  2019  1291.1325
25  2020  1313.2800
26  2021  1480.9400
27  2022  1749.5000
28  2023  1932.1375
29  2024  2296.5925


#Reliance Industries stock Analysis of 3 decades
 Reliance Industries Limited (RIL)
"The Conglomerate of India's Future"

Reliance has evolved from a textile company in the 1970s into a diversified behemoth. Its 30-year journey is marked by three distinct phases: the Petrochemical era (1990s), the Refining era (2000s), and the Consumer-Tech era (2016–Present).

Financial & Stock Performance
Wealth Compounding: From a face value of ₹10 at its 1977 IPO, the stock has multiplied thousands of times. Over the last 20 years, it climbed from approximately ₹890 (2005) to over ₹1,400 in early 2026.

Capital Intensity: Reliance is a high-Capex company. It reinvests massive portions of its EBITDA (which reached ~₹50,932 crore in Q3 FY26) back into 5G, Retail infrastructure, and New Energy.

Volatility: The stock is sensitive to global oil "cracks" and refining margins, but this volatility is increasingly dampened by its stable consumer businesses.

In [50]:
fig_Reliance = px.line(Mean_df, x='Year', y='Mean', title='Reliance Stock Price over years',labels={'Mean':'Avg Stock price in Rupee'},markers='true')

fig_Reliance.show()

fig_Reliance1 = px.bar(Mean_df, x='Year', y='Mean', title='Reliance Stock Price over years',labels={'Mean':'Avg Stock price in Rupee'},color='Mean')

fig_Reliance1.show()

#TCS Stock Analysis for 3 decades
Tata Consultancy Services (TCS)
"The Global Standard for Efficient Growth"

TCS represents the "Asset-Light" model of success. Since its 2004 listing, it has become the gold standard for Indian IT, characterized by high margins, zero debt, and massive shareholder payouts.

Financial & Stock Performance
Efficiency Leader: TCS boasts a world-class Return on Equity (ROE) of over 50%. Unlike Reliance, which borrows to grow, TCS grows through internal accruals.

Dividend Engine: TCS maintains a payout ratio of ~83%, often giving back nearly all its free cash flow to shareholders via dividends and buybacks.

In [11]:
TCS_df= Stock_df[Stock_df['Company']=='Tata Consultancy Services']
TCS_df.head(30)

,Year,Company,Open,High,Low,Close,Volume
30,1995,Tata Consultancy Services,126.61,132.00,113.18,127.47,47202575
31,1996,Tata Consultancy Services,127.47,147.06,116.95,138.48,35447928
32,1997,Tata Consultancy Services,138.48,180.87,122.24,157.95,25365176
33,1998,Tata Consultancy Services,157.95,186.36,140.10,175.96,2807460
34,1999,Tata Consultancy Services,175.96,203.21,155.94,197.92,45505028
35,2000,Tata Consultancy Services,197.92,274.01,171.96,260.68,24983185
36,2001,Tata Consultancy Services,260.68,331.86,246.25,315.79,19021373
37,2002,Tata Consultancy Services,315.79,410.77,294.43,372.68,27252959
38,2003,Tata Consultancy Services,372.68,397.68,345.41,387.87,34200653
39,2004,Tata Consultancy Services,387.87,426.08,355.51,416.84,12098292
40,2005,Tata Consultancy Services,416.84,478.82,375.27,431.44,46899769
41,2006,Tata Consultancy Services,431.44,518.48,385.85,499.56,6560202
42,2007,Tata Consultancy Services,499.56,666.75,460.68,592.01,26952878
43,2008,Tata Consultancy Services,592.01,635.87,510.38,604.76,44963572
44,2009,Tata Consultancy Services,604.76,734.11,541.50,689.91,36571828
45,2010,Tata Consultancy Services,689.91,927.31,665.98,815.84,39213901
46,2011,Tata Consultancy Services,815.84,905.02,788.77,869.36,30715023
47,2012,Tata Consultancy Services,869.36,1010.82,750.43,989.84,33511586
48,2013,Tata Consultancy Services,989.84,1387.98,870.22,1256.37,35896781
49,2014,Tata Consultancy Services,1256.37,1528.72,1121.06,1454.75,37578078
50,2015,Tata Consultancy Services,1454.75,1925.15,1344.02,1741.44,5590063
51,2016,Tata Consultancy Services,1741.44,2144.06,1540.26,2007.92,12955492
52,2017,Tata Consultancy Services,2007.92,2540.57,1871.48,2236.49,39945753
53,2018,Tata Consultancy Services,2236.49,2784.89,2068.75,2565.90,25133366
54,2019,Tata Consultancy Services,2565.90,3171.87,2189.13,3002.24,32628142
55,2020,Tata Consultancy Services,3002.24,3292.46,2918.96,3156.64,47742500
56,2021,Tata Consultancy Services,3156.64,3555.58,3064.09,3479.01,21981023
57,2022,Tata Consultancy Services,3479.01,4691.74,3392.97,4095.21,42797463
58,2023,Tata Consultancy Services,4095.21,4872.20,3649.65,4309.21,9305144
59,2024,Tata Consultancy Services,4309.21,4707.31,4182.29,4304.09,35105460

In [12]:
TCS_df['Mean'] = TCS_df[['Close','Open','High','Low']].mean(axis=1)
Mean_df1= TCS_df[['Year','Mean']]
Mean_df1.head(30)

/tmp/ipykernel_395/2628886045.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    Year       Mean
30  1995   124.8150
31  1996   132.4900
32  1997   149.8850
33  1998   165.0925
34  1999   183.2575
35  2000   226.1425
36  2001   288.6450
37  2002   348.4175
38  2003   375.9100
39  2004   396.5750
40  2005   425.5925
41  2006   458.8325
42  2007   554.7500
43  2008   585.7550
44  2009   642.5700
45  2010   774.7600
46  2011   844.7475
47  2012   905.1125
48  2013  1126.1025
49  2014  1340.2250
50  2015  1616.3400
51  2016  1858.4200
52  2017  2164.1150
53  2018  2414.0075
54  2019  2732.2850
55  2020  3092.5750
56  2021  3313.8300
57  2022  3914.7325
58  2023  4231.5675
59  2024  4375.7250

In [41]:
fig_TCS = px.line(Mean_df1, x='Year', y='Mean', title='TCS Stock Price over years',labels={'Mean':'Avg Stock price in Rupee'})

fig_TCS.update_traces(line_color='green')
fig_TCS.show()

fig_TCS1 = px.bar(Mean_df1, x='Year', y='Mean', title='TCS Stock Price over years',labels={'Mean':'Avg Stock price in Rupee'})

fig_TCS1.show()

# The Comparison in between the Gaints  
**Here** is the quick comparison in between the two gaints of indian stock market
why it is important ?
As it will tell you about 😵
.Growth v/s Stability Benchmark
.Also help us to identify the Pivot points
and we shouldn't forget uptil lAs of March 2026, Reliance remains the #1 most valuable company (~₹21.6T), while TCS remains a top 5 giant, proving that "size" doesn't stop growth if the strategy is right.

In [49]:

#combining the data frame
df_combined = pd.merge(Mean_df, Mean_df1, on='Year')
df_combined = df_combined.rename(columns={'Mean_x': 'Reliance', 'Mean_y': 'TCS'})


fig_combine1= px.line(df_combined,x='Year',y=['Reliance', 'TCS'],title='Comparison of Stock prices of Reliance and TCS',template='plotly_dark',labels={'value':'Avg Stock price in Rupee'},markers='true')
fig_combine1.show()

Comparative Equity Analysis (Reliance vs. TCS)
Overview: This report evaluates the 30-year performance trajectory of India’s two largest conglomerates: Reliance Industries Limited (RIL) and Tata Consultancy Services (TCS). While both have delivered exponential returns, they represent two distinct pillars of the Indian economy—Diversified Industrial Growth and Global Technology Services.

Financial Performance:

# Reliance Industries: Transitioned from a pure-play petrochemical firm to a consumer-tech giant. The 30-year data reflects high capital expenditure leading to dominant market share in Telecom and Retail.

# TCS: Demonstrated world-class operational efficiency. As a "dividend paymaster," it has maintained a debt-free status while consistently outperforming in Return on Equity (ROE).